name: Build docker image and release it to Azure container registry

# Example usage:
#
# jobs:
#   build-and-release:
#     uses: bergzeit/github-actions/.github/workflows/azure-docker-build-release.yml@v1
#     secrets:
#       azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
#       azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
#       azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#
# Note: The example expects the following secrets to be configured in the repository using this workflow:
# - AZURE_CLIENT_ID
# - AZURE_TENANT_ID
# - AZURE_SUBSCRIPTION_ID

on:
  workflow_call:
    inputs:
      registry_url:
        description: URL of the container registry that the image will be pushed to
        type: string
        required: false
        default: bergzeit.azurecr.io
      registry_name:
        description: Name of the container registry that the image will be pushed to
        type: string
        required: false
        default: bergzeit
      image_name:
        description: Name of the resulting image
        type: string
        required: false
        default: ${{ github.repository }}
      image_build_target:
        description: Target stage (as in Dockerfile) to build
        type: string
        required: false
    secrets:
      azure_client_id:
        description: Client ID of the Azure App Registration associated with this repository
        required: true
      azure_tenant_id:
        description: Tenant ID of the Azure App Registration associated with this repository
        required: true
      azure_subscription_id:
        description: Tenant ID of the Azure App Registration associated with this repository
        required: true

jobs:
  azure-build-and-release:
    name: Build docker image and release it to Azure container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.azure_client_id }}
            tenant-id: ${{ secrets.azure_tenant_id }}
            subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Authenticate with Azure container registry
        run: |
          az account show
          az acr login --name ${{ inputs.registry_name }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry_url }}/${{ inputs.image_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: ${{ inputs.image_build_target }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
