name: Deploy k8s manifests to aks

# Example usage:
#
# jobs:
#   deploy-aks:
#     uses: bergzeit/github-actions/.github/workflows/deploy-aks.yml@v1
#     with:
#       aks_cluster_name: ${{ secrets.AZURE_CLUSTER_NAME }}
#       aks_resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}
#       k8s_namespace: ${{ secrets.K8S_NAMESPACE }}
#       helm_chart: "./my-chart-path"
#     secrets:
#       azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
#       azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
#       azure_client_secret: "${{ secrets.AZURE_CLIENT_SECRET }}"
#       aks_subscription_id: ${{ secrets.AKS_SUBSCRIPTION_ID }}
#
# Only required values are mentioned in the example. For optional values please
# check the action definition directly.

on:
  workflow_call:
    inputs:
      aks_cluster_name:
        description: The name of the cluster to deploy to
        required: true
        type: string
      aks_resource_group:
        description: The resource group of the aks to deploy to
        required: true
        type: string
      images:
        description: Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files.
        required: false
        type: string
      imagepull_secret_name:
        description: The name of the image pull secret
        required: false
        default: imagepull-acr
        type: string
      k8s_manifests:
        description: The directory of the k8s manifest files. Defaults to ./k8s
        required: false
        default: "k8s/"
        type: string
      k8s_namespace:
        description: The namespace to deploy to
        required: true
        type: string
      registry_url:
        description: URL of the container registry that the image will be pushed to
        type: string
        required: false
        default: bergzeit.azurecr.io
      helm_chart:
        description: The path to the helm chart
        type: string
        required: true
      helm_override_files:
        description: Array of path to override files. Each path should be mentioned on a newline
        type: string
        required: false
      helm_overrides:
        description: Override values to set
        type: string
        required: false
      helm_release_name:
        description: Release name to be used for Helm option
        type: string
        required: false
      helm_arguments:
        description: Arguments to be passed to the Helm or template command
        type: string
        required: false
    secrets:
      azure_client_id:
        description: Client ID of the Azure App Registration associated with this repository
        required: true
      aks_subscription_id:
        description: The aks cluster subscription id
        required: true
      azure_tenant_id:
        description: Tenant ID of the Azure App Registration associated with this repository
        required: true
      azure_client_secret:
        description: The client secret for the azure login
        required: true

jobs:
  deploy-aks:
    name: Deploy a docker manifest from acr to aks
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      # first check out the repository for file access to k8s manifests in the deploy process
      - uses: actions/checkout@v4
      # install the kubectl cmd line tool because it is required in later steps
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4.0.0 # if you read this, please check if https://github.com/Azure/setup-kubectl/issues/100 is solved then set from v4.0.0 to v4 accordingly
        with:
          version: "latest"
        id: install
      # log in to azure for the following context creation
      - name: Authenticate with Azure
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.azure_client_id }}","clientSecret":"${{ secrets.azure_client_secret }}","subscriptionId":"${{ secrets.aks_subscription_id }}","tenantId":"${{ secrets.azure_tenant_id }}"}'
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
           kubelogin-version: 'v0.1.0' #TODO should be updated regularly 
          # set an active azure k8s context
      - name: Set aks context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "${{ inputs.aks_resource_group }}"
          cluster-name: "${{ inputs.aks_cluster_name }}"
          subscription: "${{ secrets.aks_subscription_id }}"
          use-kubelogin: true
          admin: false
        id: login
      - name: Bake helm template
        uses: Azure/k8s-bake@v2
        with:
          renderEngine: "helm"
          helmChart: "${{ inputs.helm_chart }}"
          helm-version: "latest"
          namespace: "${{ inputs.k8s_namespace }}"
          arguments: "${{ inputs.helm_arguments }}"
          overrideFiles: "${{ inputs.helm_override_files }}"
          overrides: "${{ inputs.helm_overrides }}"
          releaseName: "${{ inputs.helm_release_name }}"
          silent: "false"
        id: bake
      # deploy to the aks cluster
      - name: Deploy to aks
        uses: Azure/k8s-deploy@v4
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          action: deploy
          strategy: basic
          namespace: "${{ inputs.k8s_namespace }}"
          images: "${{ inputs.images }}"
