name: Build docker image and release it to container registry

# Example usage:
#
# jobs:
#   build-and-release:
#     uses: bergzeit/github-actions/.github/workflows/docker-build-release.yml@v1
#     secrets:
#       registry_password: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      registry:
        description: URL of the container registry that the image will be pushed to
        type: string
        required: false
        default: ghcr.io
      registry_username:
        description: Username to log into registry
        type: string
        required: false
        default: ${{ github.actor }}
      image_name:
        description: Name of the resulting image
        type: string
        required: false
        default: ${{ github.repository }}
      image_build_target:
        description: Target stage (as in Dockerfile) to build
        type: string
        required: false
      image_tag_rules:
        description: the rules how image tags will be generated
        type: string
        required: false
        default: |
          type=schedule
          type=sha  # short commit hash
          type=ref,event=tag  # raw tag
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }} # "latest" on main branch
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }} # "latest" on master branch
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }} # "latest" on develop branch
          type=raw,value=latest,enable={{ is_default_branch }}  # "latest" on project-specific default branch
      docker_context:
        type: string
        required: false
        default: .
      build_args:
        type: string
        required: false
    secrets:
      GH_ACCESS_TOKEN:
        description: The github access token for private repository access
        required: false
      registry_password:
        description: Password to log into registry
        required: true

jobs:
  build-and-release:
    name: Build docker image and release it to container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Log in to the Github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}
          tags: ${{ inputs.image_tag_rules }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker_context }}
          target: ${{ inputs.image_build_target }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            GH_ACCESS_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
            ${{ inputs.build_args }}
